## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

##this function (makeCacheMatrix) is a matrix made up
##of a list of functions that respectively set and get
##the value of a matrix and inverse of said matrix

makeCacheMatrix <- function(x = matrix()) {

  m <- NULL
  set <- function (y) {
    x <<- y
    m <<- NULL
  }
  
  get <- function() x
  setmatrix <- function(solve) m <<- solve
  getmatrix <- function() m
  list (set=set, get=get,
       setmatrix=setmatrix,
       getmatrix=getmatrix)
}


## Write a short comment describing this function

##The cacheSolve function solves, or caclulates the inverse
##of the matrix generated by the makeCacheMatrix function.
##Before computing the inverse, it first checks if the 
##inverse has already been calculated, using the stored 
##value if that is the case; if not, the function calculates the
##inverse.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  m <- x$getmatrix()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setmatrix(m)
  m
  
  }
